import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { fetchCountries } from "../api/countries/countries";
import { Country } from "../api/countries/types";

const Explorer: NextPage = () => {
  // TODO: Use React Query
  const [countries, setCountries] = useState<Country[]>([]);
  const [randomCountry, setRandomCountry] = useState<Country | undefined>(
    undefined
  );

  const updateRandomCountry = useCallback(() => {
    const randomIndex = Math.floor(Math.random() * countries.length);
    setRandomCountry(countries[randomIndex]);
  }, [countries]);

  useEffect(() => {
    if (countries.length === 0) {
      fetchCountries()
        .then((countriesResponse) => {
          setCountries(countriesResponse);
        })
        .catch((err) => {
          console.log(err);
        });
    }
  }, [countries, updateRandomCountry]);

  useEffect(() => {
    if (randomCountry === undefined) {
      updateRandomCountry();
    }
  }, [countries, randomCountry, updateRandomCountry]);

  return (
    <>
      <Head>
        <title>Destination Unknown</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-gray-50 pt-8 flex flex-col items-center">
        <div className="mx-auto py-12 px-4 flex flex-col text-center items-center justify-between">
          <h2 className="text-3xl font-extrabold tracking-tight text-gray-900 sm:text-4xl">
            <span className="block mb-4">Your next destination will be...</span>
            <span className="block text-emerald-500 text-4xl uppercase">
              {randomCountry?.name?.common ?? "..."}
            </span>
          </h2>

          <div className="inline-flex rounded-md shadow mt-8">
            <a
              onClick={updateRandomCountry}
              className="inline-flex items-center justify-center px-5 py-3 border border-transparent text-base font-medium rounded-md text-emerald-500 bg-white hover:bg-emerald-50"
            >
              New destination
            </a>
          </div>
        </div>

        <div className="flex flex-row flex-wrap w-full justify-center">
          {countries.map((country, idx) => (
            <Link
              href={`/destination/${country.name.common}`}
              passHref
              key={idx}
            >
              <a className="text-emerald-500 hover:underline">
                <div className="flex flex-row p-2">
                  <span className="block mr-2 no-underline">
                    {country.flag}
                  </span>
                  <h3 className="text-xl font-bold ">{country.name.common}</h3>
                </div>
              </a>
            </Link>
          ))}
        </div>
      </main>
    </>
  );
};

export default Explorer;
